[package]
name = "esri_ascii_grid"
version = "0.1.0"
edition = "2021"
authors = ["Seb Smith"]
description = "A library for reading ESRI Ascii Grid .asc files"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
